//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel_Macros_UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Excel_Macros_UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;!-- saved from url=(0016)http://localhost --&gt;
        ///
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=10&quot; /&gt;
        ///    &lt;script src=&quot;../Blockly/blockly_compressed.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;../Blockly/blocks_compressed.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;../Blockly/python_compressed.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;../Blockly/msg/js/en.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;host&quot; style=&quot;height: 480px; width: 600px; background: #ff6a00;&quot;&gt;&lt;/div&gt;
        ///    &lt;xml id=&quot;toolbox&quot; style=&quot;di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlocklyHost {
            get {
                return ResourceManager.GetString("BlocklyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SyntaxDefinition name=&quot;IronPython&quot; extensions=&quot;.ipy&quot;&gt;
        ///	
        ///	&lt;Properties&gt;
        ///		&lt;Property name=&quot;LineComment&quot; value=&quot;#&quot;/&gt;
        ///	&lt;/Properties&gt;
        ///	
        ///	&lt;Digits name=&quot;Digits&quot; color=&quot;#COLOR_DIGIT&quot;/&gt;
        ///
        ///	&lt;RuleSets&gt;
        ///		&lt;RuleSet ignorecase=&quot;false&quot;&gt;
        ///			
        ///			&lt;Delimiters&gt;()[]{}@,:.`=;+-*/% &amp;amp;|^&amp;gt;&amp;lt;&lt;/Delimiters&gt;
        ///			
        ///			&lt;Span name=&quot;Char&quot; stopateol=&quot;true&quot; color=&quot;#COLOR_STRING&quot; escapecharacter=&quot;\&quot;&gt;
        ///				&lt;Begin&gt;&apos;&lt;/Begin&gt;
        ///				&lt;End&gt;&apos;&lt;/End&gt;
        ///			&lt;/Span&gt;
        ///			
        ///			&lt;Span name=&quot;DocComment&quot; color=&quot;#COLOR_COMMENT&quot;&gt;
        ///				&lt;Begin&gt;&quot;&quot;&quot;&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IronPython {
            get {
                return ResourceManager.GetString("IronPython", resourceCulture);
            }
        }
    }
}
